export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  category: "AI" | "Productivity" | "Resume" | "Automation" | "Career";
  author: string;
  date: string;
  readTime: string;
  cover?: string;
  content: { type: "p" | "h2" | "h3" | "ul" | "quote"; text?: string; items?: string[] }[];
};

export const categories = ["AI", "Productivity", "Resume", "Automation", "Career"] as const;

export const blogPosts: BlogPost[] = [
  {
    slug: "ai-study-planner-guide",
    title: "How AI Study Planners Are Changing the Way Students Learn in 2026",
    description:
      "A practical guide to using AI-powered study planners to improve retention, manage time, and reduce burnout — with frameworks you can apply this week.",
    category: "AI",
    author: "Nexoras Team",
    date: "2026-05-02",
    readTime: "9 min",
    content: [
      { type: "p", text: "For decades, students have relied on paper planners, sticky notes, and a vague sense of urgency to organize their study sessions. In 2026, that approach is rapidly being replaced by AI-powered planning systems that adapt to how you actually learn. This guide breaks down what AI study planners do, why they outperform manual schedules, and how to build a routine that actually sticks." },
      { type: "h2", text: "What Is an AI Study Planner?" },
      { type: "p", text: "An AI study planner is software that takes your subjects, deadlines, energy levels, and past performance, and automatically generates a personalized schedule. Unlike traditional to-do apps, it learns from your behavior — when you focus best, which topics you struggle with, and how long tasks actually take versus how long you think they will." },
      { type: "h2", text: "Why Manual Planning Fails Most Students" },
      { type: "ul", items: [
        "We consistently underestimate how long tasks take (a phenomenon known as the planning fallacy).",
        "Static schedules don't adapt when you fall behind or get ahead.",
        "Decision fatigue makes it harder to choose what to study next as the day progresses.",
        "Manual planners don't space out revision in line with how memory actually works.",
      ]},
      { type: "h2", text: "Core Features to Look For" },
      { type: "p", text: "Not all planners are built equal. The best ones combine spaced repetition, calendar awareness, and adaptive rescheduling. When evaluating a tool, check whether it can: pull deadlines from a syllabus, suggest review sessions based on forgetting curves, and rebalance the week when something slips." },
      { type: "h3", text: "Spaced Repetition Built-In" },
      { type: "p", text: "Spaced repetition schedules increasingly long gaps between reviews, dramatically improving long-term retention. A good AI planner does this automatically, so you don't have to manage flashcard intervals manually." },
      { type: "h3", text: "Energy-Aware Scheduling" },
      { type: "p", text: "Your brain isn't equally sharp at 7am and 7pm. Modern planners ask you to log your energy patterns once, then schedule deep work (problem solving, new concepts) during peaks and lighter tasks (review, organizing notes) during dips." },
      { type: "h2", text: "A Sample Weekly Routine" },
      { type: "p", text: "Here's a routine many of our top users follow: a 90-minute deep block in the morning, a 45-minute practice session in the afternoon, and a 20-minute spaced review before bed. The AI fills in the topics based on upcoming exams and weak areas." },
      { type: "h2", text: "Common Mistakes to Avoid" },
      { type: "ul", items: [
        "Trusting the schedule blindly instead of checking in weekly.",
        "Packing every minute — leave 20% buffer for the unexpected.",
        "Ignoring rest days; recovery is when consolidation happens.",
        "Using the planner as a productivity badge instead of a tool.",
      ]},
      { type: "h2", text: "Final Thoughts" },
      { type: "p", text: "AI study planners aren't magic. They're a way to externalize the boring decisions so you can spend your mental energy on actual learning. Start small — one subject, one week — and let the system earn your trust before scaling up." },
    ],
  },
  {
    slug: "resume-mistakes-students-make",
    title: "10 Resume Mistakes Students Make (and Exactly How to Fix Them)",
    description:
      "Recruiters spend an average of 7.4 seconds scanning a resume. Here are the most common mistakes that cost students interviews, and proven fixes for each.",
    category: "Resume",
    author: "Nexoras Team",
    date: "2026-04-22",
    readTime: "8 min",
    content: [
      { type: "p", text: "Your resume is often the only thing standing between you and an interview. Yet most student resumes commit the same mistakes — over and over. After reviewing thousands of resumes, here are the patterns we see most often, and the precise fixes that move candidates from rejection to interview." },
      { type: "h2", text: "1. Listing Responsibilities Instead of Impact" },
      { type: "p", text: "\"Managed social media account\" tells the recruiter nothing. \"Grew Instagram following from 800 to 4,200 in 90 days, increasing event signups by 38%\" tells a story. Always pair what you did with a measurable result." },
      { type: "h2", text: "2. A Generic Summary at the Top" },
      { type: "p", text: "Lines like \"Hardworking student seeking opportunities\" waste prime real estate. Replace the summary with a sharp positioning statement: who you are, what you do, and what you're aiming for next." },
      { type: "h2", text: "3. Skill Soup" },
      { type: "p", text: "Long, alphabetized skill lists signal that you don't know which skills matter. Group skills into 3 to 4 buckets (Languages, Frameworks, Tools, Soft Skills) and only include items you could be quizzed on without panicking." },
      { type: "h2", text: "4. ATS-Hostile Formatting" },
      { type: "p", text: "Two-column templates, text in images, and exotic fonts often break Applicant Tracking Systems. Stick with single-column, standard fonts (Inter, Calibri, Arial), and let the template's parser see your content cleanly." },
      { type: "h2", text: "5. Burying Your Best Project" },
      { type: "p", text: "If you built something impressive, it should be visible in the top third of page one. Recruiters don't always reach the bottom." },
      { type: "h2", text: "6. Vague Project Descriptions" },
      { type: "p", text: "\"Worked on a web app\" doesn't help. Tell us the stack, your role, the problem solved, and the outcome. Three lines per project is the sweet spot." },
      { type: "h2", text: "7. Inconsistent Tense and Punctuation" },
      { type: "p", text: "Mix of past and present tense, missing periods, and irregular capitalization scream carelessness. Pick a style and apply it ruthlessly." },
      { type: "h2", text: "8. Putting GPA Front and Center When It's Below 8" },
      { type: "p", text: "If your GPA isn't a strength, don't lead with it. Lead with projects, internships, or hackathon wins instead." },
      { type: "h2", text: "9. The 2-Page Trap" },
      { type: "p", text: "Unless you have 5+ years of experience or extensive research, one page is the standard. Cut filler aggressively." },
      { type: "h2", text: "10. No Clear Call to Action" },
      { type: "p", text: "End with a portfolio link, GitHub, or LinkedIn URL — somewhere the recruiter can verify your work. Make it easy for them to say yes." },
      { type: "h2", text: "Putting It All Together" },
      { type: "p", text: "Pick three of these to fix this week. Then run your resume through an ATS checker and a real human (a senior, a mentor, a recruiter friend). Iterate. Your resume is never \"done\" — it evolves with your career." },
    ],
  },
  {
    slug: "automation-tools-for-students",
    title: "7 Automation Tools Every Student Should Know in 2026",
    description:
      "From auto-filing notes to scheduling deep work, these automation tools can save you 5+ hours every week without sacrificing quality.",
    category: "Automation",
    author: "Nexoras Team",
    date: "2026-04-15",
    readTime: "7 min",
    content: [
      { type: "p", text: "Automation isn't just for engineers. The right setup can shave hours off your week, freeing time for the work that actually matters: thinking, learning, and resting. Here are seven categories of automation every student should know about, with concrete tools and workflows for each." },
      { type: "h2", text: "1. Note Capture and Organization" },
      { type: "p", text: "Tools that turn voice memos, photos of whiteboards, and PDFs into searchable, tagged notes. The trick is to capture everything in one inbox, then let the tool sort it for you on a weekly review." },
      { type: "h2", text: "2. Smart Calendar Routing" },
      { type: "p", text: "Block your deep work, color-code subjects, and use rules to auto-decline conflicting meetings. Modern calendars can pull tasks from your planner and suggest blocks for them." },
      { type: "h2", text: "3. Reading Pipeline" },
      { type: "p", text: "Saving articles to a read-later service, then having key highlights auto-imported into your notes app, builds a personal knowledge base over time without extra effort." },
      { type: "h2", text: "4. Email Triage" },
      { type: "p", text: "Filters that auto-archive newsletters, snooze low-priority threads, and surface only what needs a reply today. Inbox zero becomes maintainable." },
      { type: "h2", text: "5. File Naming and Storage" },
      { type: "p", text: "Templates for naming files (subject_topic_date) plus auto-uploads to cloud storage prevent the dreaded \"final_v3_actuallyfinal.docx\" chaos." },
      { type: "h2", text: "6. Habit and Streak Tracking" },
      { type: "p", text: "Apps that log your study sessions automatically (via timer integrations) give honest weekly reports without you having to remember to journal." },
      { type: "h2", text: "7. AI Summaries for Long Content" },
      { type: "p", text: "When you have to read a 60-page chapter, an AI summarizer can give you a clean outline first. Then you read the full chapter knowing what to focus on." },
      { type: "h2", text: "How to Roll It Out" },
      { type: "p", text: "Don't adopt all seven at once. Pick the one that solves your biggest current pain, run it for two weeks, then add the next. Automation that you don't trust is worse than no automation." },
    ],
  },
  {
    slug: "deep-work-for-students",
    title: "The Student's Guide to Deep Work: A Repeatable System for Hard Subjects" ,
    description:
      "Deep work — focused, undistracted study on cognitively demanding tasks — is the single highest-ROI habit you can build. Here's a complete system.",
    category: "Productivity",
    author: "Nexoras Team",
    date: "2026-04-08",
    readTime: "10 min",
    content: [
      { type: "p", text: "Cal Newport coined the term \"deep work\" to describe focused, distraction-free effort on cognitively demanding tasks. For students, deep work is the difference between truly understanding a hard concept and merely highlighting paragraphs about it. This guide gives you a complete, repeatable system to make deep work part of your weekly rhythm." },
      { type: "h2", text: "Why Deep Work Matters More Than Hours Studied" },
      { type: "p", text: "Two students study the same number of hours. One spends those hours toggling between Instagram, lecture videos, and notes. The other spends them in 90-minute focused blocks. The second student will outperform the first by a wide margin — not because they're smarter, but because their attention compounded." },
      { type: "h2", text: "The 4-Step Deep Work Block" },
      { type: "ul", items: [
        "Pick one specific task with a clear finish line (e.g. \"solve problems 1–5 from Chapter 3\").",
        "Set up your environment: phone in another room, browser tabs closed, water nearby.",
        "Start a 90-minute timer. Work continuously. If you hit a wall, write down the question and keep going.",
        "Take a 15-minute walk. No phone. Let your brain consolidate.",
      ]},
      { type: "h2", text: "Common Failure Modes" },
      { type: "p", text: "Most students fail at deep work in three predictable ways: they pick tasks that are too vague, they don't protect the time, and they confuse busyness (replying to messages, organizing notes) with actual deep work." },
      { type: "h2", text: "Building the Habit" },
      { type: "p", text: "Start with one 60-minute block per day for two weeks. Once that's automatic, expand to two blocks. Most undergraduates can sustain three deep blocks a day at maximum; pushing for more usually backfires." },
      { type: "h2", text: "Recovery Is Part of the System" },
      { type: "p", text: "Deep work is metabolically expensive. Sleep, exercise, and time off your phone are the inputs that make it sustainable. Burnout isn't a badge — it's a signal that your system is broken." },
    ],
  },
  {
    slug: "ai-tools-for-resume-building",
    title: "Using AI to Write a Resume That Actually Gets Interviews",
    description:
      "AI can either make your resume sound generic, or it can be the most powerful editor you've ever had. Here's how to use it well.",
    category: "AI",
    author: "Nexoras Team",
    date: "2026-04-01",
    readTime: "8 min",
    content: [
      { type: "p", text: "AI resume builders have exploded in popularity — and quality. Used well, they help you tighten weak bullets, surface metrics you forgot, and tailor your resume per role in minutes instead of hours. Used badly, they produce generic, keyword-stuffed text that recruiters spot instantly." },
      { type: "h2", text: "What AI Is Genuinely Good At" },
      { type: "ul", items: [
        "Rewriting a vague bullet into an action-verb-driven, measurable statement.",
        "Suggesting metrics you might have overlooked (\"How many users? How big was the dataset?\").",
        "Comparing your resume against a job description for keyword gaps.",
        "Catching grammar slips and inconsistent tense.",
      ]},
      { type: "h2", text: "Where AI Falls Short" },
      { type: "p", text: "AI can't fabricate credible experience. If you didn't lead a team of 12, asking AI to claim you did is both dishonest and easy to catch in an interview. Treat AI as an editor, not a ghostwriter." },
      { type: "h2", text: "A 4-Step AI Workflow" },
      { type: "ul", items: [
        "Draft each bullet in plain language: what did you do, and what was the result?",
        "Ask the AI to rewrite each bullet in the action-verb + measurable-impact format.",
        "Paste the target job description and ask which keywords are missing.",
        "Manually verify every claim. If it's not true, rewrite it." ,
      ]},
      { type: "h2", text: "Tailoring Without Lying" },
      { type: "p", text: "Tailoring means re-ordering your existing experience and emphasizing the most relevant projects — not inventing them. AI is great for the re-ordering and emphasis. The truth is your job." },
    ],
  },
  {
    slug: "freshers-job-search-2026",
    title: "The Fresher's Job Search Playbook for 2026",
    description:
      "A step-by-step playbook for landing your first full-time role: portfolio, applications, networking, and interview prep.",
    category: "Career",
    author: "Nexoras Team",
    date: "2026-03-25",
    readTime: "11 min",
    content: [
      { type: "p", text: "The fresher job market in 2026 rewards two things: clear evidence of what you can build, and a structured search process. Talent alone isn't enough — but a candidate with average raw skills and a great process consistently beats brilliant candidates who apply randomly." },
      { type: "h2", text: "Phase 1: Build the Portfolio" },
      { type: "p", text: "Before you apply, you need 2 to 3 projects that demonstrate the skills you claim to have. Each should solve a real (even small) problem, be deployed somewhere you can link to, and have a clean README explaining the why and the how." },
      { type: "h2", text: "Phase 2: Resume and LinkedIn" },
      { type: "p", text: "One-page resume, ATS-friendly. LinkedIn headline that says what you do (not \"Aspiring Engineer\"). Featured section showcasing your top project. About section in first person, three paragraphs max." },
      { type: "h2", text: "Phase 3: Targeted Applications" },
      { type: "p", text: "Spray-and-pray applications have a low single-digit response rate. Targeted applications, where you reference the company's actual product and customize one paragraph in your cover letter, can hit 20%+." },
      { type: "h2", text: "Phase 4: Networking That Doesn't Feel Slimy" },
      { type: "p", text: "Send 5 thoughtful messages a week to people who do the work you want to do. Ask one specific question. Don't ask for a referral on the first message. Build the relationship before you need it." },
      { type: "h2", text: "Phase 5: Interview Prep" },
      { type: "p", text: "Two tracks in parallel: technical (problem solving, system design basics, fundamentals of your stack) and behavioral (STAR-format stories about your projects, conflicts, and growth)." },
      { type: "h2", text: "Tracking the Pipeline" },
      { type: "p", text: "A simple spreadsheet with columns for company, role, date applied, contact, status, and next action will keep you honest. Review it every Friday." },
    ],
  },
  {
    slug: "spaced-repetition-explained",
    title: "Spaced Repetition: The Most Effective Study Technique You Aren't Using",
    description:
      "Spaced repetition can multiply your retention 3-5x for the same study time. Here's the science and a practical setup.",
    category: "Productivity",
    author: "Nexoras Team",
    date: "2026-03-18",
    readTime: "7 min",
    content: [
      { type: "p", text: "If you've ever crammed for an exam and forgotten everything two weeks later, you've experienced the forgetting curve. Spaced repetition is the antidote — and decades of research show it's the single most effective way to lock information into long-term memory." },
      { type: "h2", text: "The Science in Plain English" },
      { type: "p", text: "Hermann Ebbinghaus mapped the forgetting curve in the 1880s: most of what you learn fades within hours unless reinforced. Spaced repetition reinforces material at expanding intervals — 1 day, 3 days, 7 days, 16 days — flattening the curve dramatically." },
      { type: "h2", text: "What to Make Cards For" },
      { type: "ul", items: [
        "Definitions you'll be tested on.",
        "Formulas where forgetting one variable kills the whole problem.",
        "Vocabulary in any language.",
        "First-line indicators that trigger the rest of a procedure (in clinical or engineering subjects).",
      ]},
      { type: "h2", text: "What NOT to Make Cards For" },
      { type: "p", text: "Skills like writing, problem solving, and creative work don't respond well to flashcards. Practice them by doing, not reviewing." },
      { type: "h2", text: "A 15-Minute Daily Setup" },
      { type: "p", text: "Open your deck, do today's reviews honestly (don't fake-rate \"easy\" to make the queue shorter), and add 5 to 10 new cards from yesterday's lectures. That's it. Compounded over a semester, this single habit can transform your grades." },
    ],
  },
  {
    slug: "personal-website-portfolio",
    title: "Why Every Student Needs a Personal Website (and How to Build One in a Weekend)",
    description:
      "A personal website is the single highest-leverage thing you can ship as a student. Here's why it matters and how to launch one fast.",
    category: "Career",
    author: "Nexoras Team",
    date: "2026-03-10",
    readTime: "6 min",
    content: [
      { type: "p", text: "Your LinkedIn looks like everyone else's LinkedIn. Your resume is one of hundreds in a folder. A personal website is the one piece of professional real estate that's entirely yours, and it pays compounding dividends throughout your career." },
      { type: "h2", text: "What It Should Contain" },
      { type: "ul", items: [
        "A clear one-line introduction: who you are and what you do.",
        "2 to 3 featured projects with screenshots, links, and a short story.",
        "A short about page with your background and what you're looking for.",
        "Contact information that actually works.",
      ]},
      { type: "h2", text: "What It Doesn't Need" },
      { type: "p", text: "A blog you'll never update, a fancy 3D scrolling animation, or a list of 47 skills with progress bars. Less is more. Recruiters spend 60 seconds on your site at most." },
      { type: "h2", text: "Tools to Build It Fast" },
      { type: "p", text: "Modern site builders let you ship a clean portfolio in a weekend. Pick one, use a template, and resist the urge to perfect the design before launching. You can iterate after it's live." },
      { type: "h2", text: "The Domain Tip" },
      { type: "p", text: "Get yourname.com if you can. It's the cheapest credibility signal you'll ever buy and lasts your entire career." },
    ],
  },
  {
    slug: "ai-ethics-in-studying",
    title: "Using AI Ethically While Studying: A Student's Framework",
    description:
      "Where's the line between AI as a tutor and AI as a shortcut that hurts your learning? A simple framework for staying on the right side of it.",
    category: "AI",
    author: "Nexoras Team",
    date: "2026-03-03",
    readTime: "6 min",
    content: [
      { type: "p", text: "AI tools are now baked into how students learn. They explain hard concepts on demand, draft essays, and summarize textbooks. The question isn't whether to use them — it's how to use them without short-circuiting your own learning." },
      { type: "h2", text: "The Test: Could You Reproduce It Tomorrow?" },
      { type: "p", text: "If an AI helps you finish an assignment but you couldn't reproduce the work tomorrow without it, you've outsourced your learning. If you could explain every line and reproduce the result, the AI was a tutor — and that's fine." },
      { type: "h2", text: "Honest Use Cases" },
      { type: "ul", items: [
        "Asking for an explanation of a concept in three different ways until one clicks.",
        "Generating practice problems to test your understanding.",
        "Getting feedback on a draft you wrote.",
        "Summarizing background reading you'll then verify.",
      ]},
      { type: "h2", text: "Dishonest Use Cases" },
      { type: "ul", items: [
        "Submitting AI-generated work as your own without disclosure.",
        "Using AI to bypass exams or take-home assessments.",
        "Skipping the thinking and copying solutions wholesale.",
      ]},
      { type: "h2", text: "Closing Thought" },
      { type: "p", text: "The students who win the AI era aren't the ones who use AI the most — they're the ones who use it deliberately. Be one of them." },
    ],
  },
  {
    slug: "weekly-review-template",
    title: "The 30-Minute Weekly Review That Quietly Transforms Your Semester",
    description:
      "A simple weekly review process that catches problems early, keeps long-term goals in sight, and makes Monday far less stressful.",
    category: "Productivity",
    author: "Nexoras Team",
    date: "2026-02-24",
    readTime: "5 min",
    content: [
      { type: "p", text: "Most students don't fail because they don't work hard. They fail because they work hard in the wrong direction for too long without noticing. A 30-minute weekly review is the cheapest, highest-leverage habit to fix that." },
      { type: "h2", text: "When to Do It" },
      { type: "p", text: "Friday evening or Sunday morning. Pick one and protect it. Treat it like a class you can't skip." },
      { type: "h2", text: "The 5-Step Template" },
      { type: "ul", items: [
        "Look back: What got done? What slipped? Why?",
        "Clean up: Inbox to zero, files filed, planner emptied of stale tasks.",
        "Look up: Any deadlines in the next 14 days? Surface them now.",
        "Look in: How am I sleeping, eating, exercising? Any red flags?",
        "Look forward: Pick the 3 most important things for next week and put them on the calendar first.",
      ]},
      { type: "h2", text: "Why It Works" },
      { type: "p", text: "Most stress comes from things you've half-forgotten lurking at the edge of awareness. A weekly review pulls them into the open, forces decisions, and gives your brain permission to actually rest the rest of the week." },
    ],
  },
];

export function getPost(slug: string) {
  return blogPosts.find((p) => p.slug === slug);
}
