/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MockTestsRouteImport } from './routes/mock-tests'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FutureCareersRouteImport } from './routes/future-careers'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EngineeringRoadmapsRouteImport } from './routes/engineering-roadmaps'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrackJeeRouteImport } from './routes/crack-jee'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetitiveExamsRouteImport } from './routes/competitive-exams'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateQuestionsRouteImport } from './routes/api/generate-questions'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsRoute = MockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureCareersRoute = FutureCareersRouteImport.update({
  id: '/future-careers',
  path: '/future-careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoadmapsRoute = EngineeringRoadmapsRouteImport.update({
  id: '/engineering-roadmaps',
  path: '/engineering-roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrackJeeRoute = CrackJeeRouteImport.update({
  id: '/crack-jee',
  path: '/crack-jee',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitiveExamsRoute = CompetitiveExamsRouteImport.update({
  id: '/competitive-exams',
  path: '/competitive-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateQuestionsRoute = ApiGenerateQuestionsRouteImport.update({
  id: '/api/generate-questions',
  path: '/api/generate-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calculators': typeof CalculatorsRoute
  '/career': typeof CareerRoute
  '/chat': typeof ChatRoute
  '/competitive-exams': typeof CompetitiveExamsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/crack-jee': typeof CrackJeeRoute
  '/dashboard': typeof DashboardRoute
  '/engineering-roadmaps': typeof EngineeringRoadmapsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-careers': typeof FutureCareersRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/mock-tests': typeof MockTestsRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/roadmaps': typeof RoadmapsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calculators': typeof CalculatorsRoute
  '/career': typeof CareerRoute
  '/chat': typeof ChatRoute
  '/competitive-exams': typeof CompetitiveExamsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/crack-jee': typeof CrackJeeRoute
  '/dashboard': typeof DashboardRoute
  '/engineering-roadmaps': typeof EngineeringRoadmapsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-careers': typeof FutureCareersRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/mock-tests': typeof MockTestsRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/roadmaps': typeof RoadmapsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calculators': typeof CalculatorsRoute
  '/career': typeof CareerRoute
  '/chat': typeof ChatRoute
  '/competitive-exams': typeof CompetitiveExamsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/crack-jee': typeof CrackJeeRoute
  '/dashboard': typeof DashboardRoute
  '/engineering-roadmaps': typeof EngineeringRoadmapsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-careers': typeof FutureCareersRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/mock-tests': typeof MockTestsRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/roadmaps': typeof RoadmapsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/calculators'
    | '/career'
    | '/chat'
    | '/competitive-exams'
    | '/contact'
    | '/courses'
    | '/crack-jee'
    | '/dashboard'
    | '/engineering-roadmaps'
    | '/forgot-password'
    | '/future-careers'
    | '/login'
    | '/mock-interview'
    | '/mock-tests'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resume'
    | '/roadmaps'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/api/chat'
    | '/api/generate-questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/calculators'
    | '/career'
    | '/chat'
    | '/competitive-exams'
    | '/contact'
    | '/courses'
    | '/crack-jee'
    | '/dashboard'
    | '/engineering-roadmaps'
    | '/forgot-password'
    | '/future-careers'
    | '/login'
    | '/mock-interview'
    | '/mock-tests'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resume'
    | '/roadmaps'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/api/chat'
    | '/api/generate-questions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/calculators'
    | '/career'
    | '/chat'
    | '/competitive-exams'
    | '/contact'
    | '/courses'
    | '/crack-jee'
    | '/dashboard'
    | '/engineering-roadmaps'
    | '/forgot-password'
    | '/future-careers'
    | '/login'
    | '/mock-interview'
    | '/mock-tests'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resume'
    | '/roadmaps'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/api/chat'
    | '/api/generate-questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CareerRoute: typeof CareerRoute
  ChatRoute: typeof ChatRoute
  CompetitiveExamsRoute: typeof CompetitiveExamsRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  CrackJeeRoute: typeof CrackJeeRoute
  DashboardRoute: typeof DashboardRoute
  EngineeringRoadmapsRoute: typeof EngineeringRoadmapsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FutureCareersRoute: typeof FutureCareersRoute
  LoginRoute: typeof LoginRoute
  MockInterviewRoute: typeof MockInterviewRoute
  MockTestsRoute: typeof MockTestsRoute
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateQuestionsRoute: typeof ApiGenerateQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests': {
      id: '/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof MockTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-careers': {
      id: '/future-careers'
      path: '/future-careers'
      fullPath: '/future-careers'
      preLoaderRoute: typeof FutureCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-roadmaps': {
      id: '/engineering-roadmaps'
      path: '/engineering-roadmaps'
      fullPath: '/engineering-roadmaps'
      preLoaderRoute: typeof EngineeringRoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crack-jee': {
      id: '/crack-jee'
      path: '/crack-jee'
      fullPath: '/crack-jee'
      preLoaderRoute: typeof CrackJeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitive-exams': {
      id: '/competitive-exams'
      path: '/competitive-exams'
      fullPath: '/competitive-exams'
      preLoaderRoute: typeof CompetitiveExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-questions': {
      id: '/api/generate-questions'
      path: '/api/generate-questions'
      fullPath: '/api/generate-questions'
      preLoaderRoute: typeof ApiGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CalculatorsRoute: CalculatorsRoute,
  CareerRoute: CareerRoute,
  ChatRoute: ChatRoute,
  CompetitiveExamsRoute: CompetitiveExamsRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  CrackJeeRoute: CrackJeeRoute,
  DashboardRoute: DashboardRoute,
  EngineeringRoadmapsRoute: EngineeringRoadmapsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FutureCareersRoute: FutureCareersRoute,
  LoginRoute: LoginRoute,
  MockInterviewRoute: MockInterviewRoute,
  MockTestsRoute: MockTestsRoute,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResumeRoute: ResumeRoute,
  RoadmapsRoute: RoadmapsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateQuestionsRoute: ApiGenerateQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
